### ISSUE TITLE
Type checkingfor Extent.from_bbox() too strict

### ISSUE THREAD

**Issue by FHunt-OS** [OrdnanceSurvey/osdatahub#22]
`Extent.from_bbox()` enforces that `bbox` is a tuple. It would be more flexible to allow a suitable length sequence instead, e.g. a list or numpy array. This would increase compatibility with other geospatial libraries that return bounds, such as geopandas.GeoDataFrame.total_bounds, which returns an array.

**Comment by E-Paine** [comment]
The merged PR has changed this to allow any 4-element collection (which includes tuples, lists, sets, numpy arrays, etc.)
