### ISSUE TITLE
Out of date link in readme

### ISSUE THREAD

**Issue by MMarochov** [OrdnanceSurvey/osdatahub#56]
In the readme under Quick Start NGD API section there is a broken link, in the following text:

Then we need to get our [OS API key](https://osdatahub.os.uk/) and store it as a variable ([find out how to do this securely with environment variables](https://github.com/OrdnanceSurvey/osdatahub/blob/modify-links/Examples/Setting%20up%20an%20API%20key.ipynb)):

**Comment by JEPooley** [comment]
Note: Currently fixed in dev branch (by @MMarochov)
